//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRadio.Resources.AddRadio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddRadioStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddRadioStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebRadio.Resources.AddRadio.AddRadioStrings", typeof(AddRadioStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Channel.
        /// </summary>
        public static string AddRadio_Header {
            get {
                return ResourceManager.GetString("AddRadio_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP LOGO HERE.
        /// </summary>
        public static string Drop_Here {
            get {
                return ResourceManager.GetString("Drop_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Path.
        /// </summary>
        public static string Image_Url {
            get {
                return ResourceManager.GetString("Image_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains invalid chars. Invalid chars are: .
        /// </summary>
        public static string Invalid_chars {
            get {
                return ResourceManager.GetString("Invalid_chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already existing.
        /// </summary>
        public static string Name_not_unique {
            get {
                return ResourceManager.GetString("Name_not_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only drop 1 file into the window..
        /// </summary>
        public static string Only_One_Image {
            get {
                return ResourceManager.GetString("Only_One_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
    }
}
